name: Publish

on:
  push:
    branches: [main]
    paths-ignore: .github/**

jobs:
  publish:
    environment:
      name: Live
      url: https://rotex1800.de
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v5
        with:
          node-version: '16'
      - run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.122.0'
          extended: true

      - name: Run Hugo
        run: |
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./public/

      - name: Upload with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: public/
          state-name: ../.ftp-deploy-sync-state.json
          server: w00a5ba0.kasserver.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
